// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "scLean_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// write_csc_to_hdf5
void write_csc_to_hdf5(std::string hdf5_path, std::string group_path, std::vector<double> data, std::vector<int> indices, std::vector<double> indptr, int n_rows, int n_cols);
RcppExport SEXP _scLean_write_csc_to_hdf5(SEXP hdf5_pathSEXP, SEXP group_pathSEXP, SEXP dataSEXP, SEXP indicesSEXP, SEXP indptrSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group_path(group_pathSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type indptr(indptrSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    write_csc_to_hdf5(hdf5_path, group_path, data, indices, indptr, n_rows, n_cols);
    return R_NilValue;
END_RCPP
}
// read_hdf5_shape
IntegerVector read_hdf5_shape(std::string hdf5_path, std::string group_path);
RcppExport SEXP _scLean_read_hdf5_shape(SEXP hdf5_pathSEXP, SEXP group_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group_path(group_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_shape(hdf5_path, group_path));
    return rcpp_result_gen;
END_RCPP
}
// read_hdf5_dense_chunk
NumericMatrix read_hdf5_dense_chunk(std::string hdf5_path, std::string group_path, int row_start, int row_count, int col_start, int col_count);
RcppExport SEXP _scLean_read_hdf5_dense_chunk(SEXP hdf5_pathSEXP, SEXP group_pathSEXP, SEXP row_startSEXP, SEXP row_countSEXP, SEXP col_startSEXP, SEXP col_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group_path(group_pathSEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_count(row_countSEXP);
    Rcpp::traits::input_parameter< int >::type col_start(col_startSEXP);
    Rcpp::traits::input_parameter< int >::type col_count(col_countSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_dense_chunk(hdf5_path, group_path, row_start, row_count, col_start, col_count));
    return rcpp_result_gen;
END_RCPP
}
// read_hdf5_as_dgCMatrix
List read_hdf5_as_dgCMatrix(std::string hdf5_path, std::string group_path);
RcppExport SEXP _scLean_read_hdf5_as_dgCMatrix(SEXP hdf5_pathSEXP, SEXP group_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group_path(group_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_as_dgCMatrix(hdf5_path, group_path));
    return rcpp_result_gen;
END_RCPP
}
// hdf5_matvec
std::vector<double> hdf5_matvec(std::string hdf5_path, std::string group_path, std::vector<double> x);
RcppExport SEXP _scLean_hdf5_matvec(SEXP hdf5_pathSEXP, SEXP group_pathSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group_path(group_pathSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hdf5_matvec(hdf5_path, group_path, x));
    return rcpp_result_gen;
END_RCPP
}
// write_strings_to_hdf5
void write_strings_to_hdf5(std::string hdf5_path, std::string path, std::vector<std::string> data);
RcppExport SEXP _scLean_write_strings_to_hdf5(SEXP hdf5_pathSEXP, SEXP pathSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type data(dataSEXP);
    write_strings_to_hdf5(hdf5_path, path, data);
    return R_NilValue;
END_RCPP
}
// read_strings_from_hdf5
std::vector<std::string> read_strings_from_hdf5(std::string hdf5_path, std::string path);
RcppExport SEXP _scLean_read_strings_from_hdf5(SEXP hdf5_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_strings_from_hdf5(hdf5_path, path));
    return rcpp_result_gen;
END_RCPP
}
// read_hdf5_int32
std::vector<int> read_hdf5_int32(std::string hdf5_path, std::string path);
RcppExport SEXP _scLean_read_hdf5_int32(SEXP hdf5_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_int32(hdf5_path, path));
    return rcpp_result_gen;
END_RCPP
}
// read_vector_int8
std::vector<int> read_vector_int8(std::string hdf5_path, std::string path);
RcppExport SEXP _scLean_read_vector_int8(SEXP hdf5_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_vector_int8(hdf5_path, path));
    return rcpp_result_gen;
END_RCPP
}
// read_hdf5_double
std::vector<double> read_hdf5_double(std::string hdf5_path, std::string path);
RcppExport SEXP _scLean_read_hdf5_double(SEXP hdf5_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_double(hdf5_path, path));
    return rcpp_result_gen;
END_RCPP
}
// read_hdf5_float32
std::vector<double> read_hdf5_float32(std::string hdf5_path, std::string path);
RcppExport SEXP _scLean_read_hdf5_float32(SEXP hdf5_pathSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_hdf5_float32(hdf5_path, path));
    return rcpp_result_gen;
END_RCPP
}
// read_dense_matrix
NumericMatrix read_dense_matrix(std::string hdf5_path, std::string dataset_path);
RcppExport SEXP _scLean_read_dense_matrix(SEXP hdf5_pathSEXP, SEXP dataset_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset_path(dataset_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_dense_matrix(hdf5_path, dataset_path));
    return rcpp_result_gen;
END_RCPP
}
// list_hdf5_groups
std::vector<std::string> list_hdf5_groups(std::string hdf5_path, std::string parent_path);
RcppExport SEXP _scLean_list_hdf5_groups(SEXP hdf5_pathSEXP, SEXP parent_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type parent_path(parent_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(list_hdf5_groups(hdf5_path, parent_path));
    return rcpp_result_gen;
END_RCPP
}
// stream_10x_to_hdf5
void stream_10x_to_hdf5(std::string tenx_dir, std::string hdf5_path, std::string assay);
RcppExport SEXP _scLean_stream_10x_to_hdf5(SEXP tenx_dirSEXP, SEXP hdf5_pathSEXP, SEXP assaySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type tenx_dir(tenx_dirSEXP);
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay(assaySEXP);
    stream_10x_to_hdf5(tenx_dir, hdf5_path, assay);
    return R_NilValue;
END_RCPP
}
// cpp_current_rss
double cpp_current_rss();
RcppExport SEXP _scLean_cpp_current_rss() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_current_rss());
    return rcpp_result_gen;
END_RCPP
}
// cpp_wall_time_ns
double cpp_wall_time_ns();
RcppExport SEXP _scLean_cpp_wall_time_ns() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_wall_time_ns());
    return rcpp_result_gen;
END_RCPP
}
// suppress_hdf5_errors
void suppress_hdf5_errors();
RcppExport SEXP _scLean_suppress_hdf5_errors() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    suppress_hdf5_errors();
    return R_NilValue;
END_RCPP
}
// cpp_set_threads
void cpp_set_threads(int n);
RcppExport SEXP _scLean_cpp_set_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    cpp_set_threads(n);
    return R_NilValue;
END_RCPP
}
// cpp_get_threads
int cpp_get_threads();
RcppExport SEXP _scLean_cpp_get_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_get_threads());
    return rcpp_result_gen;
END_RCPP
}
// cpp_resource_snapshot
Rcpp::List cpp_resource_snapshot();
RcppExport SEXP _scLean_cpp_resource_snapshot() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_resource_snapshot());
    return rcpp_result_gen;
END_RCPP
}
// cpp_bottleneck_type
std::string cpp_bottleneck_type();
RcppExport SEXP _scLean_cpp_bottleneck_type() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_bottleneck_type());
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_max_dense_chunk_mb
void cpp_set_max_dense_chunk_mb(double mb);
RcppExport SEXP _scLean_cpp_set_max_dense_chunk_mb(SEXP mbSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mb(mbSEXP);
    cpp_set_max_dense_chunk_mb(mb);
    return R_NilValue;
END_RCPP
}
// cpp_get_max_dense_chunk_mb
double cpp_get_max_dense_chunk_mb();
RcppExport SEXP _scLean_cpp_get_max_dense_chunk_mb() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_get_max_dense_chunk_mb());
    return rcpp_result_gen;
END_RCPP
}
// cpp_normalize
List cpp_normalize(std::string hdf5_path, std::string assay_group, int method, double scale_factor, int chunk_size, bool in_memory);
RcppExport SEXP _scLean_cpp_normalize(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP methodSEXP, SEXP scale_factorSEXP, SEXP chunk_sizeSEXP, SEXP in_memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type in_memory(in_memorySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_normalize(hdf5_path, assay_group, method, scale_factor, chunk_size, in_memory));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale
List cpp_scale(std::string hdf5_path, std::string assay_group, bool do_scale, bool do_center, int chunk_size, bool in_memory);
RcppExport SEXP _scLean_cpp_scale(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP do_scaleSEXP, SEXP do_centerSEXP, SEXP chunk_sizeSEXP, SEXP in_memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< bool >::type do_scale(do_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type do_center(do_centerSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type in_memory(in_memorySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale(hdf5_path, assay_group, do_scale, do_center, chunk_size, in_memory));
    return rcpp_result_gen;
END_RCPP
}
// cpp_vst
List cpp_vst(std::string hdf5_path, std::string assay_group, int n_top);
RcppExport SEXP _scLean_cpp_vst(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP n_topSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_top(n_topSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_vst(hdf5_path, assay_group, n_top));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pca
List cpp_pca(std::string hdf5_path, std::string assay_group, int npcs, double tol, int max_iter, Rcpp::Nullable<Rcpp::IntegerVector> feature_indices);
RcppExport SEXP _scLean_cpp_pca(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP npcsSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP feature_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< int >::type npcs(npcsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type feature_indices(feature_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pca(hdf5_path, assay_group, npcs, tol, max_iter, feature_indices));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_neighbors
void cpp_find_neighbors(NumericMatrix embeddings, int k, std::string metric, int n_trees, std::string hdf5_path, std::string assay_group);
RcppExport SEXP _scLean_cpp_find_neighbors(SEXP embeddingsSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP n_treesSEXP, SEXP hdf5_pathSEXP, SEXP assay_groupSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type embeddings(embeddingsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    cpp_find_neighbors(embeddings, k, metric, n_trees, hdf5_path, assay_group);
    return R_NilValue;
END_RCPP
}
// cpp_find_clusters
List cpp_find_clusters(std::string hdf5_path, std::string assay_group, int algorithm, double resolution, int n_iter);
RcppExport SEXP _scLean_cpp_find_clusters(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP algorithmSEXP, SEXP resolutionSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< int >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_clusters(hdf5_path, assay_group, algorithm, resolution, n_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_markers
List cpp_find_markers(std::string hdf5_path, std::string assay_group, std::vector<int> clusters, int ident_1, int ident_2, int test_type, double logfc_threshold, double min_pct);
RcppExport SEXP _scLean_cpp_find_markers(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP clustersSEXP, SEXP ident_1SEXP, SEXP ident_2SEXP, SEXP test_typeSEXP, SEXP logfc_thresholdSEXP, SEXP min_pctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type ident_1(ident_1SEXP);
    Rcpp::traits::input_parameter< int >::type ident_2(ident_2SEXP);
    Rcpp::traits::input_parameter< int >::type test_type(test_typeSEXP);
    Rcpp::traits::input_parameter< double >::type logfc_threshold(logfc_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type min_pct(min_pctSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_markers(hdf5_path, assay_group, clusters, ident_1, ident_2, test_type, logfc_threshold, min_pct));
    return rcpp_result_gen;
END_RCPP
}
// cpp_integrate
void cpp_integrate(std::string hdf5_path, std::string assay_group, std::vector<int> batch_labels, int n_ccs, int n_mnn, double sigma, int max_iter);
RcppExport SEXP _scLean_cpp_integrate(SEXP hdf5_pathSEXP, SEXP assay_groupSEXP, SEXP batch_labelsSEXP, SEXP n_ccsSEXP, SEXP n_mnnSEXP, SEXP sigmaSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type hdf5_path(hdf5_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type assay_group(assay_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type batch_labels(batch_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_ccs(n_ccsSEXP);
    Rcpp::traits::input_parameter< int >::type n_mnn(n_mnnSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    cpp_integrate(hdf5_path, assay_group, batch_labels, n_ccs, n_mnn, sigma, max_iter);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scLean_write_csc_to_hdf5", (DL_FUNC) &_scLean_write_csc_to_hdf5, 7},
    {"_scLean_read_hdf5_shape", (DL_FUNC) &_scLean_read_hdf5_shape, 2},
    {"_scLean_read_hdf5_dense_chunk", (DL_FUNC) &_scLean_read_hdf5_dense_chunk, 6},
    {"_scLean_read_hdf5_as_dgCMatrix", (DL_FUNC) &_scLean_read_hdf5_as_dgCMatrix, 2},
    {"_scLean_hdf5_matvec", (DL_FUNC) &_scLean_hdf5_matvec, 3},
    {"_scLean_write_strings_to_hdf5", (DL_FUNC) &_scLean_write_strings_to_hdf5, 3},
    {"_scLean_read_strings_from_hdf5", (DL_FUNC) &_scLean_read_strings_from_hdf5, 2},
    {"_scLean_read_hdf5_int32", (DL_FUNC) &_scLean_read_hdf5_int32, 2},
    {"_scLean_read_vector_int8", (DL_FUNC) &_scLean_read_vector_int8, 2},
    {"_scLean_read_hdf5_double", (DL_FUNC) &_scLean_read_hdf5_double, 2},
    {"_scLean_read_hdf5_float32", (DL_FUNC) &_scLean_read_hdf5_float32, 2},
    {"_scLean_read_dense_matrix", (DL_FUNC) &_scLean_read_dense_matrix, 2},
    {"_scLean_list_hdf5_groups", (DL_FUNC) &_scLean_list_hdf5_groups, 2},
    {"_scLean_stream_10x_to_hdf5", (DL_FUNC) &_scLean_stream_10x_to_hdf5, 3},
    {"_scLean_cpp_current_rss", (DL_FUNC) &_scLean_cpp_current_rss, 0},
    {"_scLean_cpp_wall_time_ns", (DL_FUNC) &_scLean_cpp_wall_time_ns, 0},
    {"_scLean_suppress_hdf5_errors", (DL_FUNC) &_scLean_suppress_hdf5_errors, 0},
    {"_scLean_cpp_set_threads", (DL_FUNC) &_scLean_cpp_set_threads, 1},
    {"_scLean_cpp_get_threads", (DL_FUNC) &_scLean_cpp_get_threads, 0},
    {"_scLean_cpp_resource_snapshot", (DL_FUNC) &_scLean_cpp_resource_snapshot, 0},
    {"_scLean_cpp_bottleneck_type", (DL_FUNC) &_scLean_cpp_bottleneck_type, 0},
    {"_scLean_cpp_set_max_dense_chunk_mb", (DL_FUNC) &_scLean_cpp_set_max_dense_chunk_mb, 1},
    {"_scLean_cpp_get_max_dense_chunk_mb", (DL_FUNC) &_scLean_cpp_get_max_dense_chunk_mb, 0},
    {"_scLean_cpp_normalize", (DL_FUNC) &_scLean_cpp_normalize, 6},
    {"_scLean_cpp_scale", (DL_FUNC) &_scLean_cpp_scale, 6},
    {"_scLean_cpp_vst", (DL_FUNC) &_scLean_cpp_vst, 3},
    {"_scLean_cpp_pca", (DL_FUNC) &_scLean_cpp_pca, 6},
    {"_scLean_cpp_find_neighbors", (DL_FUNC) &_scLean_cpp_find_neighbors, 6},
    {"_scLean_cpp_find_clusters", (DL_FUNC) &_scLean_cpp_find_clusters, 5},
    {"_scLean_cpp_find_markers", (DL_FUNC) &_scLean_cpp_find_markers, 8},
    {"_scLean_cpp_integrate", (DL_FUNC) &_scLean_cpp_integrate, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_scLean(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
