# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_csc_to_hdf5 <- function(hdf5_path, group_path, data, indices, indptr, n_rows, n_cols) {
    invisible(.Call(`_scLean_write_csc_to_hdf5`, hdf5_path, group_path, data, indices, indptr, n_rows, n_cols))
}

read_hdf5_shape <- function(hdf5_path, group_path) {
    .Call(`_scLean_read_hdf5_shape`, hdf5_path, group_path)
}

read_hdf5_dense_chunk <- function(hdf5_path, group_path, row_start, row_count, col_start, col_count) {
    .Call(`_scLean_read_hdf5_dense_chunk`, hdf5_path, group_path, row_start, row_count, col_start, col_count)
}

read_hdf5_as_dgCMatrix <- function(hdf5_path, group_path) {
    .Call(`_scLean_read_hdf5_as_dgCMatrix`, hdf5_path, group_path)
}

hdf5_matvec <- function(hdf5_path, group_path, x) {
    .Call(`_scLean_hdf5_matvec`, hdf5_path, group_path, x)
}

write_strings_to_hdf5 <- function(hdf5_path, path, data) {
    invisible(.Call(`_scLean_write_strings_to_hdf5`, hdf5_path, path, data))
}

read_strings_from_hdf5 <- function(hdf5_path, path) {
    .Call(`_scLean_read_strings_from_hdf5`, hdf5_path, path)
}

read_hdf5_int32 <- function(hdf5_path, path) {
    .Call(`_scLean_read_hdf5_int32`, hdf5_path, path)
}

read_vector_int8 <- function(hdf5_path, path) {
    .Call(`_scLean_read_vector_int8`, hdf5_path, path)
}

read_hdf5_double <- function(hdf5_path, path) {
    .Call(`_scLean_read_hdf5_double`, hdf5_path, path)
}

read_hdf5_float32 <- function(hdf5_path, path) {
    .Call(`_scLean_read_hdf5_float32`, hdf5_path, path)
}

read_dense_matrix <- function(hdf5_path, dataset_path) {
    .Call(`_scLean_read_dense_matrix`, hdf5_path, dataset_path)
}

list_hdf5_groups <- function(hdf5_path, parent_path) {
    .Call(`_scLean_list_hdf5_groups`, hdf5_path, parent_path)
}

cpp_normalize <- function(hdf5_path, assay_group, method, scale_factor, chunk_size, in_memory) {
    .Call(`_scLean_cpp_normalize`, hdf5_path, assay_group, method, scale_factor, chunk_size, in_memory)
}

cpp_scale <- function(hdf5_path, assay_group, do_scale, do_center, chunk_size, in_memory) {
    .Call(`_scLean_cpp_scale`, hdf5_path, assay_group, do_scale, do_center, chunk_size, in_memory)
}

cpp_vst <- function(hdf5_path, assay_group, n_top) {
    .Call(`_scLean_cpp_vst`, hdf5_path, assay_group, n_top)
}

cpp_pca <- function(hdf5_path, assay_group, npcs, tol, max_iter, feature_indices) {
    .Call(`_scLean_cpp_pca`, hdf5_path, assay_group, npcs, tol, max_iter, feature_indices)
}

cpp_find_neighbors <- function(embeddings, k, metric, n_trees, hdf5_path, assay_group) {
    invisible(.Call(`_scLean_cpp_find_neighbors`, embeddings, k, metric, n_trees, hdf5_path, assay_group))
}

cpp_find_clusters <- function(hdf5_path, assay_group, algorithm, resolution, n_iter) {
    .Call(`_scLean_cpp_find_clusters`, hdf5_path, assay_group, algorithm, resolution, n_iter)
}

cpp_find_markers <- function(hdf5_path, assay_group, clusters, ident_1, ident_2, test_type, logfc_threshold, min_pct) {
    .Call(`_scLean_cpp_find_markers`, hdf5_path, assay_group, clusters, ident_1, ident_2, test_type, logfc_threshold, min_pct)
}

cpp_integrate <- function(hdf5_path, assay_group, batch_labels, n_ccs, n_mnn = 20L, sigma = 0.1, max_iter = 2L) {
    invisible(.Call(`_scLean_cpp_integrate`, hdf5_path, assay_group, batch_labels, n_ccs, n_mnn, sigma, max_iter))
}

cpp_current_rss <- function() {
    .Call(`_scLean_cpp_current_rss`)
}

cpp_wall_time_ns <- function() {
    .Call(`_scLean_cpp_wall_time_ns`)
}

suppress_hdf5_errors <- function() {
    invisible(.Call(`_scLean_suppress_hdf5_errors`))
}

cpp_set_threads <- function(n) {
    invisible(.Call(`_scLean_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
    .Call(`_scLean_cpp_get_threads`)
}

cpp_resource_snapshot <- function() {
    .Call(`_scLean_cpp_resource_snapshot`)
}

cpp_bottleneck_type <- function() {
    .Call(`_scLean_cpp_bottleneck_type`)
}

cpp_set_max_dense_chunk_mb <- function(mb) {
    invisible(.Call(`_scLean_cpp_set_max_dense_chunk_mb`, mb))
}

cpp_get_max_dense_chunk_mb <- function() {
    .Call(`_scLean_cpp_get_max_dense_chunk_mb`)
}

stream_10x_to_hdf5 <- function(tenx_dir, hdf5_path, assay = "RNA") {
    invisible(.Call(`_scLean_stream_10x_to_hdf5`, tenx_dir, hdf5_path, assay))
}

